export const getSafeUser = (user) => ({
  _id: user._id,
  firstName: user.firstName,
  lastName: user.lastName,
  fullName: user.fullName,
  email: user.email,
  number: user.number,
  isActive: user.isActive,
  isProvider: user.isProvider,
  avatar: user.avatarUrl,
  location: user.location,
  bio: user.bio,
  providerStatus: user.providerProfile?.applicationStatus ?? null,
  submittedAt: user.providerProfile?.submittedAt ?? null,
  isApplicationAttampted: user?.isAttampted ?? null,
});
